"use client";

import { api } from "@pdp/backend/convex/_generated/api";
import type { Id } from "@pdp/backend/convex/_generated/dataModel";
import { useAction } from "convex/react";
import {
  Activity,
  Calendar,
  CheckCircle2,
  Download,
  Dumbbell,
  Lightbulb,
  Share2,
  Sparkles,
  Target,
  Trophy,
  User,
  X,
} from "lucide-react";
import { useCallback, useState } from "react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

type AIPracticeAssistantProps = {
  playerData: Array<{
    player: {
      _id: Id<"playerIdentities">;
      firstName: string;
      lastName: string;
    };
  }>;
  orgId: string;
};

type PracticePlan = {
  playerName: string;
  sport: string;
  ageGroup: string;
  weeklyFocus: string;
  targetSkills: Array<{
    name: string;
    currentRating: number;
    targetRating: number;
  }>;
  primaryGoal: string;
  drills: Array<{
    name: string;
    duration: string;
    skill: string;
    instructions: string[];
    successMetric: string;
    aiTip: string;
  }>;
  schedule: Array<{
    day: string;
    time: string;
    duration: string;
  }>;
  equipment: string[];
  weeklyGoal: string;
  progressTracking: string[];
  parentTips: string[];
};

export function AIPracticeAssistantEnhanced({
  playerData,
  orgId,
}: AIPracticeAssistantProps) {
  const [selectedChildId, setSelectedChildId] = useState<string | null>(null);
  const [generatedPlan, setGeneratedPlan] = useState<PracticePlan | null>(null);
  const [showPlanDialog, setShowPlanDialog] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);

  // AI practice plan generation action
  const generatePlanAction = useAction(
    api.actions.practicePlans.generatePracticePlan
  );

  // Generate practice plan using AI
  const generatePlan = useCallback(async () => {
    if (!selectedChildId) {
      return;
    }

    setIsGenerating(true);

    try {
      const plan = await generatePlanAction({
        playerIdentityId: selectedChildId as Id<"playerIdentities">,
        organizationId: orgId,
      });

      setGeneratedPlan(plan);
      setShowPlanDialog(true);
      toast.success("Practice plan generated!");
    } catch (error) {
      console.error("Failed to generate practice plan:", error);
      toast.error(
        error instanceof Error
          ? error.message
          : "Failed to generate practice plan"
      );
    } finally {
      setIsGenerating(false);
    }
  }, [selectedChildId, orgId, generatePlanAction]);

  // Share/download practice plan
  const handleShare = () => {
    if (!generatedPlan) {
      return;
    }

    // Create text version of plan
    const planText = `
${generatedPlan.playerName}'s Weekly Practice Plan
${generatedPlan.sport} • ${generatedPlan.ageGroup}

WEEKLY FOCUS: ${generatedPlan.weeklyFocus}
GOAL: ${generatedPlan.primaryGoal}

RECOMMENDED SCHEDULE:
${generatedPlan.schedule.map((s) => `• ${s.day} - ${s.time} (${s.duration})`).join("\n")}

PRACTICE DRILLS:
${generatedPlan.drills
  .map(
    (drill, idx) => `
${idx + 1}. ${drill.name} (${drill.duration})
   Focus: ${drill.skill}

   Instructions:
   ${drill.instructions.map((inst, i) => `   ${i + 1}. ${inst}`).join("\n")}

   Success Metric: ${drill.successMetric}
   💡 Coach Tip: ${drill.aiTip}
`
  )
  .join("\n")}

EQUIPMENT NEEDED:
${generatedPlan.equipment.map((e) => `• ${e}`).join("\n")}

WEEKLY GOAL:
${generatedPlan.weeklyGoal}

PARENT TIPS:
${generatedPlan.parentTips.map((tip, i) => `${i + 1}. ${tip}`).join("\n")}

PROGRESS TRACKING:
${generatedPlan.progressTracking.map((item) => `☐ ${item}`).join("\n")}

Generated by PlayerARC AI Practice Assistant
    `.trim();

    // Use native share if available
    if (navigator.share) {
      navigator
        .share({
          title: `${generatedPlan.playerName}'s Practice Plan`,
          text: planText,
        })
        .catch((error) => {
          if (error.name !== "AbortError") {
            console.error("Share failed:", error);
          }
        });
    } else {
      // Fallback: Copy to clipboard
      navigator.clipboard.writeText(planText).then(() => {
        toast.success("Practice plan copied to clipboard!");
      });
    }
  };

  const handleDownload = () => {
    if (!generatedPlan) {
      return;
    }

    // Create downloadable text file
    const planText = `${generatedPlan.playerName}'s Weekly Practice Plan\n${generatedPlan.sport} • ${generatedPlan.ageGroup}\n\nWEEKLY FOCUS: ${generatedPlan.weeklyFocus}\nGOAL: ${generatedPlan.primaryGoal}\n\nRECOMMENDED SCHEDULE:\n${generatedPlan.schedule.map((s) => `• ${s.day} - ${s.time} (${s.duration})`).join("\n")}\n\nPRACTICE DRILLS:\n${generatedPlan.drills.map((drill, idx) => `\n${idx + 1}. ${drill.name} (${drill.duration})\n   Focus: ${drill.skill}\n   \n   Instructions:\n   ${drill.instructions.map((inst, i) => `   ${i + 1}. ${inst}`).join("\n")}\n   \n   Success Metric: ${drill.successMetric}\n   💡 Coach Tip: ${drill.aiTip}\n`).join("\n")}\n\nEQUIPMENT NEEDED:\n${generatedPlan.equipment.map((e) => `• ${e}`).join("\n")}\n\nWEEKLY GOAL:\n${generatedPlan.weeklyGoal}\n\nPARENT TIPS:\n${generatedPlan.parentTips.map((tip, i) => `${i + 1}. ${tip}`).join("\n")}\n\nPROGRESS TRACKING:\n${generatedPlan.progressTracking.map((item) => `☐ ${item}`).join("\n")}\n\nGenerated by PlayerARC AI Practice Assistant`;

    const blob = new Blob([planText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `practice-plan-${generatedPlan.playerName.replace(/\s+/g, "-").toLowerCase()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success("Practice plan downloaded!");
  };

  return (
    <>
      <Card className="overflow-hidden">
        <CardHeader className="bg-gradient-to-r from-purple-600 to-purple-700 text-white">
          <CardTitle className="flex items-center gap-2 text-white">
            <Sparkles className="h-5 w-5" />
            AI Practice Assistant
          </CardTitle>
          <CardDescription className="text-purple-100">
            Generate personalized 15-minute home practice plans powered by AI
          </CardDescription>
        </CardHeader>
        <CardContent className="p-4">
          <div className="space-y-4">
            <div>
              <label
                className="mb-2 block font-medium text-sm"
                htmlFor="child-select"
              >
                Select Child
              </label>
              <Select
                onValueChange={setSelectedChildId}
                value={selectedChildId || ""}
              >
                <SelectTrigger id="child-select">
                  <SelectValue placeholder="Choose a child" />
                </SelectTrigger>
                <SelectContent>
                  {playerData.map((child) => (
                    <SelectItem key={child.player._id} value={child.player._id}>
                      <div className="flex items-center gap-2">
                        <User className="h-4 w-4" />
                        {child.player.firstName} {child.player.lastName}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <Button
              className="w-full bg-purple-600 hover:bg-purple-700"
              disabled={!selectedChildId || isGenerating}
              onClick={generatePlan}
            >
              {isGenerating ? (
                <>
                  <Sparkles className="mr-2 h-4 w-4 animate-spin" />
                  Generating with AI...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4" />
                  Generate AI Practice Plan
                </>
              )}
            </Button>

            <div className="rounded-lg bg-purple-50 p-3">
              <h4 className="mb-2 flex items-center gap-2 font-medium text-purple-800 text-sm">
                <Lightbulb className="h-4 w-4" />
                How it works
              </h4>
              <ul className="space-y-1 text-purple-700 text-xs">
                <li>• AI analyzes skill ratings and coach feedback</li>
                <li>• Identifies areas for improvement</li>
                <li>• Creates personalized sport-specific drills</li>
                <li>• 3 × 5-minute drills = 15 mins total</li>
                <li>• Includes coaching tips for parents</li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Practice Plan Dialog */}
      <Dialog onOpenChange={setShowPlanDialog} open={showPlanDialog}>
        <DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto">
          <DialogHeader>
            <div className="flex items-center justify-between">
              <div>
                <DialogTitle className="flex items-center gap-2">
                  <Sparkles className="h-5 w-5 text-purple-600" />
                  Weekly Practice Plan
                </DialogTitle>
                <DialogDescription>
                  {generatedPlan?.playerName} • {generatedPlan?.sport} •{" "}
                  {generatedPlan?.ageGroup}
                </DialogDescription>
              </div>
              <Button
                onClick={() => setShowPlanDialog(false)}
                size="icon"
                variant="ghost"
              >
                <X className="h-4 w-4" />
              </Button>
            </div>
          </DialogHeader>

          {generatedPlan && (
            <div className="space-y-6">
              {/* Weekly Focus */}
              <div className="rounded-lg border-purple-500 border-l-4 bg-purple-50 p-4">
                <div className="mb-2 flex items-start gap-3">
                  <Target className="mt-1 h-6 w-6 flex-shrink-0 text-purple-600" />
                  <div className="flex-1">
                    <h4 className="mb-2 font-bold text-purple-900">
                      This Week's Focus
                    </h4>
                    <p className="mb-2 font-medium text-gray-800 text-lg">
                      {generatedPlan.weeklyFocus}
                    </p>
                    <p className="text-gray-700 text-sm">
                      <strong>Linked to Goal:</strong>{" "}
                      {generatedPlan.primaryGoal}
                    </p>
                    {generatedPlan.targetSkills.length > 0 && (
                      <div className="mt-3">
                        <p className="mb-1 font-medium text-gray-700 text-xs">
                          Target Skills:
                        </p>
                        <div className="flex flex-wrap gap-2">
                          {generatedPlan.targetSkills.map((skill) => (
                            <Badge
                              className="bg-purple-100 text-purple-700"
                              key={skill.name}
                              variant="outline"
                            >
                              {skill.name}: {skill.currentRating} →{" "}
                              {skill.targetRating}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* Schedule */}
              <div>
                <h4 className="mb-3 flex items-center gap-2 font-semibold">
                  <Calendar className="h-5 w-5 text-purple-600" />
                  Recommended Practice Times
                </h4>
                <div className="grid grid-cols-3 gap-3">
                  {generatedPlan.schedule.map((session) => (
                    <div
                      className="rounded-lg border-2 border-purple-200 bg-purple-50 p-3"
                      key={session.day}
                    >
                      <p className="font-semibold text-purple-900">
                        {session.day}
                      </p>
                      <p className="text-gray-600 text-sm">{session.time}</p>
                      <p className="font-medium text-purple-600 text-xs">
                        {session.duration}
                      </p>
                    </div>
                  ))}
                </div>
                <p className="mt-2 text-gray-500 text-xs">
                  💡 Consistent timing helps build routine and commitment
                </p>
              </div>

              {/* Drills */}
              <div>
                <h4 className="mb-3 flex items-center gap-2 font-semibold">
                  <Activity className="h-5 w-5 text-purple-600" />
                  Practice Drills (15 minutes total)
                </h4>
                <div className="space-y-4">
                  {generatedPlan.drills.map((drill, idx) => (
                    <div
                      className="rounded-lg border border-gray-200 p-4 transition-shadow hover:shadow-md"
                      key={drill.name}
                    >
                      <div className="mb-3 flex items-start justify-between">
                        <div className="flex-1">
                          <h5 className="font-bold text-gray-800">
                            Drill {idx + 1}: {drill.name}
                          </h5>
                          <p className="text-gray-600 text-sm">
                            Duration: {drill.duration} • Focus: {drill.skill}
                          </p>
                        </div>
                        <Badge className="bg-purple-100 text-purple-700">
                          {drill.duration}
                        </Badge>
                      </div>

                      <div className="mb-3 space-y-2">
                        <p className="font-semibold text-gray-700 text-sm">
                          Instructions:
                        </p>
                        <ol className="ml-4 space-y-1 text-gray-600 text-sm">
                          {drill.instructions.map((instruction) => (
                            <li className="list-decimal" key={instruction}>
                              {instruction}
                            </li>
                          ))}
                        </ol>
                      </div>

                      <div className="mb-2 rounded border-green-500 border-l-4 bg-green-50 p-3">
                        <p className="mb-1 flex items-center gap-1 font-semibold text-green-900 text-xs">
                          <CheckCircle2 className="h-3 w-3" /> Success Metric:
                        </p>
                        <p className="text-gray-700 text-sm">
                          {drill.successMetric}
                        </p>
                      </div>

                      <div className="rounded border-blue-500 border-l-4 bg-blue-50 p-3">
                        <p className="mb-1 flex items-center gap-1 font-semibold text-blue-900 text-xs">
                          <Lightbulb className="h-3 w-3" /> AI Coaching Tip:
                        </p>
                        <p className="text-gray-700 text-sm">{drill.aiTip}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Equipment */}
              <div className="rounded-lg bg-gray-50 p-4">
                <h4 className="mb-3 flex items-center gap-2 font-semibold">
                  <Dumbbell className="h-5 w-5 text-purple-600" />
                  Equipment Needed
                </h4>
                <ul className="grid grid-cols-2 gap-2">
                  {generatedPlan.equipment.map((item) => (
                    <li
                      className="flex items-center gap-2 text-gray-700 text-sm"
                      key={item}
                    >
                      <span className="text-purple-600">✓</span> {item}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Weekly Goal */}
              <div className="rounded-lg border-yellow-500 border-l-4 bg-yellow-50 p-4">
                <h4 className="mb-2 flex items-center gap-2 font-semibold text-yellow-900">
                  <Trophy className="h-5 w-5" />
                  Weekly Goal
                </h4>
                <p className="text-gray-700">{generatedPlan.weeklyGoal}</p>
              </div>

              {/* Parent Tips */}
              {generatedPlan.parentTips.length > 0 && (
                <div className="rounded-lg bg-green-50 p-4">
                  <h4 className="mb-3 flex items-center gap-2 font-semibold text-green-900">
                    👨‍👩‍👧 Tips for Parents
                  </h4>
                  <ul className="space-y-2">
                    {generatedPlan.parentTips.map((tip, idx) => (
                      <li
                        className="flex items-start gap-2 text-gray-700 text-sm"
                        key={tip}
                      >
                        <span className="font-bold text-green-600">
                          {idx + 1}.
                        </span>
                        <span>{tip}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Progress Tracking */}
              <div>
                <h4 className="mb-3 font-semibold">📊 Track Your Progress</h4>
                <ul className="space-y-2">
                  {generatedPlan.progressTracking.map((item) => (
                    <li
                      className="flex items-start gap-2 text-gray-700 text-sm"
                      key={item}
                    >
                      <input className="mt-1" type="checkbox" />
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Action Buttons */}
              <div className="flex gap-3 border-t pt-4">
                <Button
                  className="flex-1 bg-purple-600 hover:bg-purple-700"
                  onClick={handleShare}
                >
                  <Share2 className="mr-2 h-4 w-4" />
                  Share Practice Plan
                </Button>
                <Button onClick={handleDownload} variant="outline">
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </Button>
              </div>

              {/* AI Disclaimer */}
              <p className="text-center text-gray-500 text-xs italic">
                This plan was generated by AI based on{" "}
                {generatedPlan.playerName}
                's current skill levels, coach feedback, and development goals.
                Adjust as needed for your child's comfort and progress.
              </p>
            </div>
          )}
        </DialogContent>
      </Dialog>
    </>
  );
}
