/**
 * Analytics Tracker for Session Plans
 *
 * Centralized event tracking with PostHog integration.
 * Safely handles cases where PostHog is not available.
 */

import { sessionPlanConfig } from "./session-plan-config";

// Creation method types
export type SessionPlanCreationMethod =
  | "ai_generated" // Generated by AI (OpenAI/Anthropic)
  | "manual_ui" // Created manually via UI (future feature)
  | "imported" // Imported from external source (future feature)
  | "template"; // Created from template (future feature)

// Type-safe event properties
type SessionPlanEventProps = {
  teamId: string;
  teamName: string;
  playerCount?: number;
  ageGroup?: string;
  creationMethod?: SessionPlanCreationMethod; // How the plan was created
  usedRealAI?: boolean; // DEPRECATED: Use creationMethod instead
  cacheHit?: boolean;
  cacheAge?: number; // milliseconds
  focus?: string;
  planId?: string;
};

/**
 * Track a session plan event
 * Falls back to console logging if PostHog is not available
 */
export function trackSessionPlanEvent(
  eventName: string,
  properties?: SessionPlanEventProps
) {
  // Try to use PostHog if available
  if (typeof window !== "undefined") {
    try {
      // Import posthog dynamically to ensure it's available
      const { default: posthog } = require("posthog-js");

      // Check if PostHog is initialized
      if (posthog.__loaded) {
        posthog.capture(eventName, {
          ...properties,
          timestamp: Date.now(),
          source: "smart-coach-dashboard",
        });
        console.log(`[Analytics] ✅ ${eventName}`, properties);
        return;
      }

      console.warn(`[Analytics] ⚠️ PostHog not loaded yet for ${eventName}`);
    } catch (error) {
      console.error("[Analytics] ❌ PostHog error:", error);
    }
  }

  // Fallback: Log to console in development
  if (process.env.NODE_ENV === "development") {
    console.log(`[Analytics] ${eventName}`, properties);
  }
}

/**
 * Track session plan generation
 */
export function trackPlanGenerated(props: SessionPlanEventProps) {
  trackSessionPlanEvent(sessionPlanConfig.events.PLAN_GENERATED, {
    ...props,
    cacheHit: false,
  });
}

/**
 * Track session plan cache hit
 */
export function trackPlanCached(props: SessionPlanEventProps) {
  trackSessionPlanEvent(sessionPlanConfig.events.PLAN_CACHED, {
    ...props,
    cacheHit: true,
  });
}

/**
 * Track session plan regeneration
 */
export function trackPlanRegenerated(props: SessionPlanEventProps) {
  trackSessionPlanEvent(sessionPlanConfig.events.PLAN_REGENERATED, props);
}

/**
 * Track session plan sharing
 */
export function trackPlanShared(
  props: SessionPlanEventProps & { shareMethod?: string }
) {
  trackSessionPlanEvent(sessionPlanConfig.events.PLAN_SHARED, props);
}

/**
 * Track session plan viewing (when modal opens)
 */
export function trackPlanViewed(props: SessionPlanEventProps) {
  trackSessionPlanEvent(sessionPlanConfig.events.PLAN_VIEWED, props);
}
